apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-server-ci
  name: go-server-ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-server-ci
  template:
    metadata:
      labels:
        app: go-server-ci
    spec:
      containers:
        - image: ghcr.io/2023-4400-exp/4410-go-server-ci:6e434051b96596ef0f6b32ce152bf61cbddf542c
          name: go-server-ci
